apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    app: windows2019-installation
  name: windows2019-installation
  namespace: default
  annotations:
    name.os.template.kubevirt.io/win2k19: Microsoft Windows Server 2019
    description: windows2019-installation
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/domain: windows2019-installation
        vm.kubevirt.io/name: windows2019-installation
        workload.template.kubevirt.io/server: 'true'
    spec:
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
            - bootOrder: 2
              cdrom:
                bus: sata
              name: disk-0
            - cdrom:
                bus: sata
              name: windows-guest-tools
            - cdrom:
                bus: sata
              name: win-installation-scripts
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel8.2.0
        resources:
          requests:
            memory: 8Gi
      evictionStrategy: LiveMigrate
      hostname: windows2019-installation
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - containerDisk:
            image: registry.redhat.io/container-native-virtualization/virtio-win
          name: windows-guest-tools
        - name: rootdisk
          emptyDisk:
            capacity: "12Gi"
        - name: disk-0
          persistentVolumeClaim:
            claimName: windows-iso
        - configMap:
            name: win-installation-scripts
          name: win-installation-scripts
